import { computeStandings } from '@domain/standings/computeStandings';

import { resolveRoundRobin, seedOfSlot } from '../roundRobin';
import { generateRoundRobin } from '../roundRobin/generate';
import { VALID } from '../types';

import { distributeSlots } from './distribute';

import type {
  GeneratedStructure,
  ResolveInput,
  ResolvedStructure,
  Standing,
  StandingsInput,
  TournamentFormat,
  ValidationResult,
} from '../types';
import type { GroupStageConfig, ParticipantId, StageId } from '@models/index';

const MAX_GROUPS = 16;
const MAX_SLOTS = 128;

/**
 * Builds a group stage: several round robins running side by side.
 *
 * Each group is generated by the round robin code rather than a copy of it — a
 * group *is* a round robin, and the only difference is that its matches carry a
 * group index. Two implementations would drift the moment a scheduling detail
 * changes.
 */
export function generateGroupStage(input: {
  stageId: StageId;
  config: GroupStageConfig;
  slotCount: number;
}): GeneratedStructure {
  const { stageId, config, slotCount } = input;

  const groups = distributeSlots(
    slotCount,
    config.groupCount,
    config.distribution,
    stageId,
    config.groups,
  );

  const matches: GeneratedStructure['matches'] = [];
  const rounds: GeneratedStructure['rounds'] = [];

  groups.forEach((slotIndices, groupIndex) => {
    if (slotIndices.length < 2) return;

    const group = generateRoundRobin({
      stageId,
      shape: {
        slotCount,
        legs: config.perGroup.legs,
        matchFormat: config.perGroup.matchFormat,
        groupIndex,
        slotIndices,
      },
    });

    matches.push(...group.matches);
    // Rounds are reported once, from the largest group: they run in parallel, so
    // "round 2" means the same thing in every group.
    if (group.rounds.length > rounds.length) {
      rounds.length = 0;
      rounds.push(...group.rounds);
    }
  });

  return { stageId, slotCount, matches, rounds };
}

/** Group membership as participants, derived the same way the structure was. */
export function groupsOf(
  config: GroupStageConfig,
  stageId: StageId,
  slotCount: number,
  seededSlots: ReadonlyMap<number, ParticipantId>,
): ParticipantId[][] {
  return distributeSlots(
    slotCount,
    config.groupCount,
    config.distribution,
    stageId,
    config.groups,
  ).map((slots) =>
    slots
      .map((slotIndex) => seededSlots.get(slotIndex))
      .filter((id): id is ParticipantId => id !== undefined),
  );
}

/**
 * One table per group.
 *
 * Kept separate from the flat standings because a group stage has no single
 * table: comparing a participant from group A with one from group B on points
 * alone would be meaningless, since they faced different opponents.
 */
export function groupStandings(input: StandingsInput<GroupStageConfig>): Standing[][] {
  const { structure, config, seededSlots, storedMatches } = input;
  const groups = groupsOf(config, structure.stageId, seededSlots.size, seededSlots);

  return groups.map((participants, groupIndex) =>
    computeStandings({
      participants,
      matches: structure.matches.filter((match) => match.position.groupIndex === groupIndex),
      storedMatches: storedMatches ?? new Map(),
      pointSystem: config.perGroup.pointSystem,
      tiebreakers: config.perGroup.tiebreakers,
      seedOf: (participantId) => seedOfSlot(seededSlots, participantId),
    }),
  );
}

/**
 * A flat ranking across all groups.
 *
 * Ordered by placement within the group first, so every group winner outranks
 * every runner-up. That is what a following stage means by "the top two of each
 * group", and it makes the flat list usable for seeding without inventing a
 * cross-group comparison of points.
 */
function flatStandings(input: StandingsInput<GroupStageConfig>): Standing[] {
  const tables = groupStandings(input);
  const flat: Standing[] = [];

  const deepest = tables.reduce((max, table) => Math.max(max, table.length), 0);
  for (let place = 1; place <= deepest; place += 1) {
    for (const table of tables) {
      for (const entry of table) {
        if (entry.rank === place) flat.push({ ...entry, rank: flat.length + 1 });
      }
    }
  }

  return flat;
}

function validate(config: GroupStageConfig, slotCount: number): ValidationResult {
  const issues = [];

  if (config.groupCount < 1) {
    issues.push({
      code: 'group_stage.no_groups',
      severity: 'error' as const,
      message: 'A group stage needs at least one group.',
    });
  }

  if (config.groupCount > MAX_GROUPS) {
    issues.push({
      code: 'group_stage.too_many_groups',
      severity: 'error' as const,
      message: `At most ${String(MAX_GROUPS)} groups are supported.`,
    });
  }

  if (slotCount > MAX_SLOTS) {
    issues.push({
      code: 'group_stage.too_many_participants',
      severity: 'error' as const,
      message: `At most ${String(MAX_SLOTS)} participants are supported.`,
    });
  }

  // Fewer than two per group means groups that cannot play a single match.
  if (config.groupCount >= 1 && slotCount < config.groupCount * 2) {
    issues.push({
      code: 'group_stage.groups_too_small',
      severity: 'error' as const,
      message: 'Each group needs at least two participants.',
    });
  }

  return issues.length === 0 ? VALID : { valid: false, issues };
}

/** Groups run independently, so resolution is the round robin one. */
function resolve(input: ResolveInput): ResolvedStructure {
  return resolveRoundRobin(input);
}

export const groupStageFormat: TournamentFormat<GroupStageConfig> = {
  kind: 'group_stage',
  generateStructure: generateGroupStage,
  resolveSlots: resolve,
  computeStandings: flatStandings,
  computeGroupStandings: groupStandings,
  validate,
};

export { distributeSlots } from './distribute';
